version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install



artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
